// app/api/invoice/create/route.ts
import { NextResponse } from "next/server";
import { Resend } from "resend";

export const runtime = "nodejs";

type LineItem = { name: string; qty: number; unit_price: number };

const resendKey = process.env.RESEND_API_KEY || "";
const FROM = process.env.RESEND_FROM || "support@adoraops.com";
const resend = resendKey ? new Resend(resendKey) : null;

function safeStr(v: any) {
  return String(v ?? "").trim();
}
function asNum(v: any) {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}
function isEmail(s: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}
function money(n: number) {
  return n.toFixed(2);
}

function renderDoc(opts: {
  kind: "invoice" | "receipt";
  businessName?: string;
  to: string;
  items: LineItem[];
  note?: string;
  docNumber?: string;
  dateISO?: string;
}) {
  const kindTitle = opts.kind === "invoice" ? "Invoice" : "Receipt";
  const date = opts.dateISO ? new Date(opts.dateISO) : new Date();
  const docNo = opts.docNumber || `${kindTitle.toUpperCase()}-${date.getTime()}`;

  const subtotal = opts.items.reduce(
    (sum, it) => sum + it.qty * it.unit_price,
    0
  );
  const total = subtotal;

  const rows = opts.items
    .map((it) => {
      const line = it.qty * it.unit_price;
      return `
        <tr>
          <td style="padding:10px;border-bottom:1px solid #E6E8EE;"><b>${escapeHtml(
            it.name
          )}</b></td>
          <td style="padding:10px;border-bottom:1px solid #E6E8EE;text-align:right;">${it.qty}</td>
          <td style="padding:10px;border-bottom:1px solid #E6E8EE;text-align:right;">$${money(
            it.unit_price
          )}</td>
          <td style="padding:10px;border-bottom:1px solid #E6E8EE;text-align:right;">$${money(
            line
          )}</td>
        </tr>
      `;
    })
    .join("");

  const note = safeStr(opts.note);

  return {
    docNo,
    subtotal,
    total,
    html: `
      <div style="font-family:Inter,system-ui,Segoe UI,Roboto,Arial;max-width:720px;margin:0 auto;padding:18px;">
        <div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;">
          <div>
            <div style="font-size:22px;font-weight:900;color:#0B1220;">${escapeHtml(
              opts.businessName || "Adora Ops"
            )}</div>
            <div style="margin-top:6px;color:#5B6475;font-size:13px;">Generated by Adora Ops Assistant</div>
          </div>

          <div style="text-align:right;">
            <div style="font-size:18px;font-weight:900;color:#0B1220;">${kindTitle}</div>
            <div style="margin-top:4px;color:#5B6475;font-size:13px;"># ${escapeHtml(
              docNo
            )}</div>
            <div style="margin-top:4px;color:#5B6475;font-size:13px;">${date.toLocaleDateString()}</div>
          </div>
        </div>

        <div style="margin-top:14px;border:1px solid #E6E8EE;border-radius:14px;padding:14px;background:#fff;">
          <div style="color:#5B6475;font-size:12px;font-weight:800;">BILLED TO</div>
          <div style="margin-top:6px;font-weight:900;color:#0B1220;">${escapeHtml(
            opts.to
          )}</div>
        </div>

        <div style="margin-top:14px;border:1px solid #E6E8EE;border-radius:14px;overflow:hidden;background:#fff;">
          <table style="width:100%;border-collapse:collapse;">
            <thead>
              <tr style="background:#F7F9FC;">
                <th style="padding:10px;text-align:left;color:#0B1220;">Item</th>
                <th style="padding:10px;text-align:right;color:#0B1220;">Qty</th>
                <th style="padding:10px;text-align:right;color:#0B1220;">Unit</th>
                <th style="padding:10px;text-align:right;color:#0B1220;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${rows}
            </tbody>
          </table>
        </div>

        <div style="margin-top:14px;display:flex;justify-content:flex-end;">
          <div style="width:320px;border:1px solid #E6E8EE;border-radius:14px;padding:14px;background:#F7F9FC;">
            <div style="display:flex;justify-content:space-between;color:#5B6475;font-weight:800;">
              <span>Subtotal</span><span>$${money(subtotal)}</span>
            </div>
            <div style="display:flex;justify-content:space-between;margin-top:10px;color:#0B1220;font-weight:900;font-size:16px;">
              <span>Total</span><span>$${money(total)}</span>
            </div>
          </div>
        </div>

        ${
          note
            ? `<div style="margin-top:14px;color:#5B6475;font-size:13px;line-height:1.4;"><b>Note:</b> ${escapeHtml(
                note
              )}</div>`
            : ""
        }

        <div style="margin-top:18px;color:#5B6475;font-size:12px;">
          Need help? Reply to this email or contact support@adoraops.com
        </div>
      </div>
    `,
  };
}

function escapeHtml(s: string) {
  return String(s || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const kind = safeStr(body?.kind) === "receipt" ? "receipt" : "invoice";
    const to = safeStr(body?.to);
    const note = safeStr(body?.note);
    const sendEmail = Boolean(body?.send_email);

    const itemsRaw = Array.isArray(body?.items) ? body.items : [];
    const items: LineItem[] = itemsRaw
      .map((it: any) => ({
        name: safeStr(it?.name) || "Item",
        qty: Math.max(1, Math.round(asNum(it?.qty) || 1)),
        unit_price: Math.max(0, asNum(it?.unit_price)),
      }))
      .slice(0, 50);

    if (!to || !isEmail(to)) {
      return NextResponse.json(
        { ok: false, error: "Invalid or missing email (to)" },
        { status: 400 }
      );
    }
    if (!items.length) {
      return NextResponse.json(
        { ok: false, error: "Missing invoice items" },
        { status: 400 }
      );
    }

    const doc = renderDoc({
      kind,
      to,
      items,
      note,
      businessName: "Adora Ops",
    });

    if (sendEmail) {
      if (!resend) {
        return NextResponse.json(
          { ok: false, error: "Missing RESEND_API_KEY" },
          { status: 500 }
        );
      }

      const subject =
        kind === "invoice"
          ? `Invoice ${doc.docNo} from Adora Ops`
          : `Receipt ${doc.docNo} from Adora Ops`;

      await resend.emails.send({
        from: FROM,
        to: [to],
        subject,
        html: doc.html,
        text: `${subject}\nTotal: $${money(doc.total)}`,
      } as any);
    }

    return NextResponse.json({
      ok: true,
      docNo: doc.docNo,
      subtotal: doc.subtotal,
      total: doc.total,
      html: doc.html, // useful for preview in-app later
      sent: sendEmail,
    });
  } catch (e: any) {
    return NextResponse.json(
      { ok: false, error: e?.message || "Invoice create failed" },
      { status: 500 }
    );
  }
}
